### ISSUE TITLE
How to get a JSON response from curl to your website?

### ISSUE THREAD

**Issue by kopeboy** [dev-ptera/spyglass-api#62]
I would like to use your wonderful service (thank you!). I tried for example:
```
curl -X POST https://spyglass-api.web.app/v2/account/confirmed-transactions
   -H 'Content-Type: application/json'               
   -d '{ address: "ban_1..." }'
```
but I receive back an HTML document with styles and scripts.. without the Response content shown at https://spyglass-api.web.app/account/confirmed
Is the API designed to provide a JSON response from your domain? How to use it? Thank you.

**Comment by dev-ptera** [comment]
https://spyglass-api.web.app/

hey there, you’re using the wrong URL when sending requests. Check out the instructions and sample post request on the page above.
